#!/bin/bash
xhost +
docker run -it --rm --name=kinco_driver \
--ulimit memlock=-1 \
--privileged \
--device=/dev/:/dev/:rw \
--device=/dev/ttyUSB0:/dev/ttyUSB0:rw \
--env="DISPLAY=$DISPLAY" \
--volume $(pwd)/src_files/src:/root/workspace/src:rw \
--network=host \
test:latest bash

